#include <linux/ioctl.h>

#define TESTCHAR_IOC_MAGIC 'j'
#define TESTCHAR_IOCRESET _IO(TESTCHAR_IOC_MAGIC, 0)
#define TESTCHAR_ALLLOWER _IOW(TESTCHAR_IOC_MAGIC, 1, int)
#define TESTCHAR_ALLUPPER _IOW(TESTCHAR_IOC_MAGIC, 2, int)
#define TESTCHAR_ALLCAPS  _IOW(TESTCHAR_IOC_MAGIC, 3, int)
#define TESTCHAR_NONE     _IOW(TESTCHAR_IOC_MAGIC, 4, int)