#include <linux/ioctl.h>

#define TESTCHAR_IOC_MAGIC 'j'
#define TESTCHAR_IOCRESET _IO(TESTCHAR_IOC_MAGIC, 0)
#define TESTCHAR_ALLLOWER _IO(TESTCHAR_IOC_MAGIC, 1)
#define TESTCHAR_ALLUPPER _IO(TESTCHAR_IOC_MAGIC, 2)
#define TESTCHAR_ALLCAPS  _IO(TESTCHAR_IOC_MAGIC, 3)
#define TESTCHAR_NONE     _IO(TESTCHAR_IOC_MAGIC, 4)